dataset_builder: &ds_builder
    table_path: '/home/studio-lab-user/captcha/configs/table.txt'
    img_shape: [200, 50, 1]

train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        '/home/studio-lab-user/data/captcha.csv'

    batch_size_per_replica: 512
    num_kfold: 10
    # Number of epochs to train.
    epochs: 6
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0
