dataset_builder: &ds_builder
    vocab_path: 'captcha/configs/captcha_vocab.txt'
    img_width: 200
    img_height: 50
    channel: 1

train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        'captcha/configs/df_captcha.csv'

    batch_size_per_replica: 16
    num_kfold: 10
    # Number of epochs to train.
    epochs: 100
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0
    earlystopping:
        patience: 10
    fit_verbose: 0
