dataset_builder: &ds_builder
    table_path: '/content/drive/MyDrive/data/table.txt'
    # If change image height(32), change the net.
    # If image width is not null, the image will be distorted.
    img_shape: [60, 160, 3]

train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        '/content/drive/MyDrive/data/captcha.csv'

    batch_size_per_replica: 256
    # Number of epochs to train.
    epochs: 20
    lr_schedule:
        initial_learning_rate: 0.0001
        decay_steps: 600000
        alpha: 0.01
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0