dataset_builder: &ds_builder
    table_path: '/kaggle/working/table.txt'
    # If change image height(32), change the net.
    # If image width is not null, the image will be distorted.
    img_shape: [60, 200, 3]

train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        '/kaggle/input/captchabeamdataset/train_csv/train_k0.csv'
    val_csv_path:
        '/kaggle/input/captchabeamdataset/train_csv/test_k1.csv'
    batch_size_per_replica: 256
    # Number of epochs to train.
    epochs: 60
    lr_schedule:
        initial_learning_rate: 0.0001
        decay_steps: 600000
        alpha: 0.01
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0

eval:
    dataset_builder:
        <<: *ds_builder
    csv_path:
        '/kaggle/input/captchabeamdataset/train_csv/test_k1.csv'
    batch_size: 128