dataset_builder: &ds_builder
    table_path: '/home/studio-lab-user/ocr_crnn/configs/handwriting_table.txt'
    img_width: 128
    img_height: 32
    channel: 1
    is_handwriting: True
train:
    dataset_builder:
        <<: *ds_builder
    train_csv_path:
        '/home/studio-lab-user/handwriting/handwriting.csv'

    batch_size_per_replica: 64
    num_kfold: 5
    # Number of epochs to train.
    epochs: 50
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0
    earlystopping:
        patience: 10
    fit_verbose: 0
